"""
This type stub file was generated by cyright.
"""

log = ...
def _table_entry_size(name: bytes, value: bytes) -> int:
    """
    Calculates the size of a single entry

    This size is mostly irrelevant to us and defined
    specifically to accommodate memory management for
    lower level implementations. The 32 extra bytes are
    considered the "maximum" overhead that would be
    required to represent each entry in the table.

    See RFC7541 Section 4.1
    """
    ...

class HeaderTable:
    """
    Implements the combined static and dynamic header table

    The name and value arguments for all the functions
    should ONLY be byte strings (b'') however this is not
    strictly enforced in the interface.

    See RFC7541 Section 2.3
    """
    def __init__(self) -> None:
        ...
    
    def get_by_index(self, index: int) -> tuple:
        """
        Returns the entry specified by index

        Note that the table is 1-based ie an index of 0 is
        invalid.  This is due to the fact that a zero value
        index signals that a completely unindexed header
        follows.

        The entry will either be from the static table or
        the dynamic table depending on the value of index.
        """
        ...
    
    def __repr__(self) -> str:
        ...
    
    def add(self, name: bytes, value: bytes) -> object:
        """
        Adds a new entry to the table

        We reduce the table size if the entry will make the
        table size greater than maxsize.
        """
        ...
    
    def search(self, name: bytes, value: bytes) -> object:
        """
        Searches the table for the entry specified by name
        and value

        Returns one of the following:
            - ``None``, no match at all
            - ``(index, name, None)`` for partial matches on name only.
            - ``(index, name, value)`` for perfect matches.
        """
        ...
    
    @property
    def maxsize(self) -> int:
        ...
    
    @maxsize.setter
    def maxsize(self, newmax: int) -> None:
        ...
    
    def _shrink(self) -> object:
        """
        Shrinks the dynamic table to be at or below maxsize
        """
        ...
    


